### ISSUE TITLE
Doesn't run on macOS Catalina

### ISSUE THREAD

**Issue by flippette** [rodrigosetti/sdl-mandelbrot#3]
Hi,
I'm using macOS Catalina and after compiling with Make, it doesn't run

System version: macOS Catalina 10.15.1
Make version: GNU Make 4.2.1

The window just appears, takes system resources and does literally nothing. It just stays blank.

<img width="1440" alt="Screen Shot 2019-12-20 at 19 46 14" src="https://user-images.githubusercontent.com/43138244/71255747-64e8ce00-2361-11ea-8332-8c7bb1343433.png">

**Comment by gunayorbay** [comment]
SDL2 seems to be required for Catalina. See #4.

**Comment by rodrigosetti** [comment]
Thanks for the PR 👍
